WIP: fix MDBF-414
MariaDB/mariadb.org-tools pull request #156
Opened 2022-05-18 08:46 UTC by fauust

@grooverdan how could I test my changes without merging, do you want me to add the same logic as for install/upgrade script (see: https://github.com/MariaDB/mariadb.org-tools/blob/master/buildbot.mariadb.org/scripts/bash_lib.sh#L28).

One suggested approach is that we know that https://buildbot.mariadb.org/#/builders/311/builds/9150 does not clean the environment. So I could compare 2 run (one before the patch and the one after).

2022-05-18 08:51 UTC, fauust commented
And now https://buildbot.mariadb.org/#/builders/311/builds/9150 passes :) I just rebuild https://buildbot.mariadb.org/#/builders/311/builds/8838. Not sure that I understand exactly what the problem is, I need to understand better this script.

2022-05-18 09:23 UTC, grooverdan requested changes
I haven't looked at bash_lib.sh yet.

The general principle with this script is that it will get invoked for each architecture, and when the magic number of expected architectures is reached in line L235 (on the original), the manifest is pushed.

Between runs it needs to maintain its incomplete state. An important consequence of this is that the end of the script needs to clear the `trap EXIT` handler so we aren't purging out a manifest before its completed by subsequent build runs.

We are relying a lot of the L247 onwards to clear out partial manifests and their images that are incomplete because the build wasn't triggered for arch X/Y/Z. A failure bb trigger could preemptively clearly these. This would leave the case of a retrigger happy user or bb restarts that are handled.

There could also be logical that a re-triggered build replaces a image in the manifest of the same arch rather than adding to it otherwise we get like [10.9-mdev-20119-misc](https://quay.io/repository/mariadb-foundation/mariadb-devel?tab=tags) 3x arm64 builds. But overall this is a nice to have.

2022-05-18 09:23 UTC, grooverdan commented on buildbot.mariadb.org/scripts/docker-library-build-and-test.sh
its about this point we need a `buildah rm "${container}"` in the `EXIT` trap to remove the in build container.

2022-05-18 13:56 UTC, fauust commented
> I haven't looked at bash_lib.sh yet.

The idea is that instead of using positional arguments or having to call the script with all needed arguments (or settings env vars), you only need to provide the build URL from buildbot and it will get all env variables directly from the BB API. This could even be applied for any invocation of the script (via BB or manually) but as discussed with @vladbogo it's going to generate more calls on BB API and it's probably less scalable. And if we find a way to template or create generic function for build/test calls from BB then the benefit of this is lesser in simplifying BB configuration files.

Finally the `bash_lib.sh` provide logging options that permits more homogeneity (and easier maintenance if we decide to log things differently in the future).

2022-05-23 03:18 UTC, grooverdan commented
Need to clear the `trap EXIT` at the end and then I'm happy with this as a major improvement.

2022-05-23 09:41 UTC, fauust commented
> Need to clear the `trap EXIT` at the end and then I'm happy with this as a major improvement.

Not sure what you mean...

2022-05-26 05:19 UTC, grooverdan commented
Without clearing the `trap EXIT` handler at the end of this script, it will execute the handler on successful exit. This is undesireable as the build of quay.io manifests relies on the state (i.e. incomplete manifest and images) to exist in future runs for [other build architecutes](https://github.com/MariaDB/mariadb.org-tools/pull/156#pullrequestreview-976597256) which push when the right number of architecture images are in the manifest and ready to be pushed.

2022-05-30 15:55 UTC, fauust commented
Done.

2022-05-31 02:01 UTC, merged